#!/usr/bin/env python3
import subprocess
import os
import sys

filepath = '/etc/hosts'

args = sys.argv
command = args[1]
site = args[2]

if site is None:
    print("Error: Site name not provided")

if os.getuid() != 0:
    raise PermissionError("This script must be run as a root.")


def block(filepath, site):
    write_this = f"\n127.0.0.1 www.{site}.com"
    try:
        with open(filepath, 'a') as file:
            file.write(write_this)

    except PermissionError:
        print("Permission denied. Try running this script as sudo.")

    except Exception as e:
        print(f"Error occured: {e}")


def unblock(filepath, site):
    with open(filepath,  'r') as file:
        lines = file.readlines()
    with open(filepath, 'w') as file:
        for line in lines:
            if site not in line:
                file.write(line)


def refresh():
    subprocess.run(["sudo", "systemctl", "restart", "nscd"], check=True)
    subprocess.run(["sudo", "systemctl", "restart",
                   "systemd-resolved"], check=True)


def main():
    if command == "block":
        block(filepath, site)

    elif command == "unblock":
        unblock(filepath, site)

    else:
        print("Command not recognized")

    refresh()


if __name__ == "__main__":
    main()
